name: Test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout
      ref: ${{ github.ref }}

    - uses: ./
      name: Release Please
      with:
        release-type: simple
        changelog-notes-type: github
